spring:
#  jpa:
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt:
    secret: CHANGE_ME